# Generated by Django 4.0.4 on 2022-06-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_number', models.CharField(max_length=4)),
                ('Amount_paid', models.CharField(max_length=10)),
                ('Occupant_name', models.CharField(max_length=100)),
                ('Occupant_email', models.EmailField(max_length=254)),
                ('Occupant_Occupation', models.CharField(max_length=50)),
                ('Number_of_night', models.CharField(max_length=100)),
                ('Start_date', models.DateTimeField(auto_now_add=True)),
                ('End_date', models.CharField(max_length=100)),
            ],
        ),
    ]
